/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMyRegistrationsRouteImport } from './routes/_authenticated/my-registrations'
import { Route as AuthenticatedMyEventsRouteImport } from './routes/_authenticated/my-events'
import { Route as AuthenticatedDelegationsRouteImport } from './routes/_authenticated/delegations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events.new'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminOrganizationsRouteImport } from './routes/_authenticated/admin.organizations'
import { Route as AuthenticatedAdminDelegationsRouteImport } from './routes/_authenticated/admin.delegations'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin.approvals'
import { Route as AuthenticatedEventsSlugRegisterRouteImport } from './routes/_authenticated/events.$slug.register'
import { Route as AuthenticatedEventsIdRegistrationsRouteImport } from './routes/_authenticated/events.$id.registrations'
import { Route as AuthenticatedEventsIdManageRouteImport } from './routes/_authenticated/events.$id.manage'
import { Route as AuthenticatedAdminOrganizationsIdRouteImport } from './routes/_authenticated/admin.organizations.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRegistrationsRoute =
  AuthenticatedMyRegistrationsRouteImport.update({
    id: '/my-registrations',
    path: '/my-registrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyEventsRoute = AuthenticatedMyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDelegationsRoute =
  AuthenticatedDelegationsRouteImport.update({
    id: '/delegations',
    path: '/delegations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminOrganizationsRoute =
  AuthenticatedAdminOrganizationsRouteImport.update({
    id: '/admin/organizations',
    path: '/admin/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDelegationsRoute =
  AuthenticatedAdminDelegationsRouteImport.update({
    id: '/admin/delegations',
    path: '/admin/delegations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/admin/approvals',
    path: '/admin/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsSlugRegisterRoute =
  AuthenticatedEventsSlugRegisterRouteImport.update({
    id: '/events/$slug/register',
    path: '/events/$slug/register',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdRegistrationsRoute =
  AuthenticatedEventsIdRegistrationsRouteImport.update({
    id: '/events/$id/registrations',
    path: '/events/$id/registrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsIdManageRoute =
  AuthenticatedEventsIdManageRouteImport.update({
    id: '/events/$id/manage',
    path: '/events/$id/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrganizationsIdRoute =
  AuthenticatedAdminOrganizationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminOrganizationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delegations': typeof AuthenticatedDelegationsRoute
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/my-registrations': typeof AuthenticatedMyRegistrationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/delegations': typeof AuthenticatedAdminDelegationsRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/events/$id/manage': typeof AuthenticatedEventsIdManageRoute
  '/events/$id/registrations': typeof AuthenticatedEventsIdRegistrationsRoute
  '/events/$slug/register': typeof AuthenticatedEventsSlugRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delegations': typeof AuthenticatedDelegationsRoute
  '/my-events': typeof AuthenticatedMyEventsRoute
  '/my-registrations': typeof AuthenticatedMyRegistrationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events': typeof EventsIndexRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/delegations': typeof AuthenticatedAdminDelegationsRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/events/$id/manage': typeof AuthenticatedEventsIdManageRoute
  '/events/$id/registrations': typeof AuthenticatedEventsIdRegistrationsRoute
  '/events/$slug/register': typeof AuthenticatedEventsSlugRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/delegations': typeof AuthenticatedDelegationsRoute
  '/_authenticated/my-events': typeof AuthenticatedMyEventsRoute
  '/_authenticated/my-registrations': typeof AuthenticatedMyRegistrationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/delegations': typeof AuthenticatedAdminDelegationsRoute
  '/_authenticated/admin/organizations': typeof AuthenticatedAdminOrganizationsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/admin/organizations/$id': typeof AuthenticatedAdminOrganizationsIdRoute
  '/_authenticated/events/$id/manage': typeof AuthenticatedEventsIdManageRoute
  '/_authenticated/events/$id/registrations': typeof AuthenticatedEventsIdRegistrationsRoute
  '/_authenticated/events/$slug/register': typeof AuthenticatedEventsSlugRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/delegations'
    | '/my-events'
    | '/my-registrations'
    | '/profile'
    | '/events/$slug'
    | '/events/'
    | '/admin/approvals'
    | '/admin/delegations'
    | '/admin/organizations'
    | '/admin/users'
    | '/events/new'
    | '/admin/organizations/$id'
    | '/events/$id/manage'
    | '/events/$id/registrations'
    | '/events/$slug/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/delegations'
    | '/my-events'
    | '/my-registrations'
    | '/profile'
    | '/events/$slug'
    | '/events'
    | '/admin/approvals'
    | '/admin/delegations'
    | '/admin/organizations'
    | '/admin/users'
    | '/events/new'
    | '/admin/organizations/$id'
    | '/events/$id/manage'
    | '/events/$id/registrations'
    | '/events/$slug/register'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/delegations'
    | '/_authenticated/my-events'
    | '/_authenticated/my-registrations'
    | '/_authenticated/profile'
    | '/events/$slug'
    | '/events/'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/delegations'
    | '/_authenticated/admin/organizations'
    | '/_authenticated/admin/users'
    | '/_authenticated/events/new'
    | '/_authenticated/admin/organizations/$id'
    | '/_authenticated/events/$id/manage'
    | '/_authenticated/events/$id/registrations'
    | '/_authenticated/events/$slug/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-registrations': {
      id: '/_authenticated/my-registrations'
      path: '/my-registrations'
      fullPath: '/my-registrations'
      preLoaderRoute: typeof AuthenticatedMyRegistrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-events': {
      id: '/_authenticated/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof AuthenticatedMyEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delegations': {
      id: '/_authenticated/delegations'
      path: '/delegations'
      fullPath: '/delegations'
      preLoaderRoute: typeof AuthenticatedDelegationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/organizations': {
      id: '/_authenticated/admin/organizations'
      path: '/admin/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/delegations': {
      id: '/_authenticated/admin/delegations'
      path: '/admin/delegations'
      fullPath: '/admin/delegations'
      preLoaderRoute: typeof AuthenticatedAdminDelegationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$slug/register': {
      id: '/_authenticated/events/$slug/register'
      path: '/events/$slug/register'
      fullPath: '/events/$slug/register'
      preLoaderRoute: typeof AuthenticatedEventsSlugRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/registrations': {
      id: '/_authenticated/events/$id/registrations'
      path: '/events/$id/registrations'
      fullPath: '/events/$id/registrations'
      preLoaderRoute: typeof AuthenticatedEventsIdRegistrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$id/manage': {
      id: '/_authenticated/events/$id/manage'
      path: '/events/$id/manage'
      fullPath: '/events/$id/manage'
      preLoaderRoute: typeof AuthenticatedEventsIdManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/organizations/$id': {
      id: '/_authenticated/admin/organizations/$id'
      path: '/$id'
      fullPath: '/admin/organizations/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminOrganizationsRoute
    }
  }
}

interface AuthenticatedAdminOrganizationsRouteChildren {
  AuthenticatedAdminOrganizationsIdRoute: typeof AuthenticatedAdminOrganizationsIdRoute
}

const AuthenticatedAdminOrganizationsRouteChildren: AuthenticatedAdminOrganizationsRouteChildren =
  {
    AuthenticatedAdminOrganizationsIdRoute:
      AuthenticatedAdminOrganizationsIdRoute,
  }

const AuthenticatedAdminOrganizationsRouteWithChildren =
  AuthenticatedAdminOrganizationsRoute._addFileChildren(
    AuthenticatedAdminOrganizationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDelegationsRoute: typeof AuthenticatedDelegationsRoute
  AuthenticatedMyEventsRoute: typeof AuthenticatedMyEventsRoute
  AuthenticatedMyRegistrationsRoute: typeof AuthenticatedMyRegistrationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminDelegationsRoute: typeof AuthenticatedAdminDelegationsRoute
  AuthenticatedAdminOrganizationsRoute: typeof AuthenticatedAdminOrganizationsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedEventsIdManageRoute: typeof AuthenticatedEventsIdManageRoute
  AuthenticatedEventsIdRegistrationsRoute: typeof AuthenticatedEventsIdRegistrationsRoute
  AuthenticatedEventsSlugRegisterRoute: typeof AuthenticatedEventsSlugRegisterRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDelegationsRoute: AuthenticatedDelegationsRoute,
  AuthenticatedMyEventsRoute: AuthenticatedMyEventsRoute,
  AuthenticatedMyRegistrationsRoute: AuthenticatedMyRegistrationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
  AuthenticatedAdminDelegationsRoute: AuthenticatedAdminDelegationsRoute,
  AuthenticatedAdminOrganizationsRoute:
    AuthenticatedAdminOrganizationsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedEventsIdManageRoute: AuthenticatedEventsIdManageRoute,
  AuthenticatedEventsIdRegistrationsRoute:
    AuthenticatedEventsIdRegistrationsRoute,
  AuthenticatedEventsSlugRegisterRoute: AuthenticatedEventsSlugRegisterRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
